version: '3'
services:
  app:
    build: .
    command: > 
      bash -c "rm -f tmp/pids/server.pid &&
      bundle exec rails s -p 3000 -b '0.0.0.0' &&
      rails webpacker:installs &&
      rails webpacker:compile"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:15.1-bullseye
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_volume: